[WOTC_PGOverhaul.X2Helpers_PGOverhaulExperimentalItems]

; Need the tech to be added via Template Master or such
;+arrUnlockExperimentalItem=(ItemName="VestName", TechName="TechName",   TechImage="img:///UILibrary_StrategyImages.X2InventoryIcons.Inv_Microservo_Module")
