[TraversalChanger.X2DLCInfo_TraversalChanger]

;* ============================== INFORMATION ==============================

;* All character groups can be found in CharacterGroups.txt
;* All character names can be found in CharacterNames.txt
;* All ability icons can be found in AbilityIcons.txt
;* All item icons can be found in ItemIcons.txt

; Only enable log if you know what you're doing.
; This mod logs a lot of data
bLog = false