;* Hello !
;* This is the main config file for my "Traversal changer" mod, as the mod is very heavily config driven, it can be hard to parse for people not familiar with Xcom's config files
;* I tried to make it easy to use, but don't be afraid to ask for help in the "Config help" Discussion
;* This mod has 3 distinct part :

;* - Ability creation : creates all of the Traversal changing abilities (include passive, active and removal abilities)
;* - Item / Vest creation : optionally, create vests & items that can have those abilities
;* - Applying abilities : To who the new abilities are created, can be a unit (AdvCaptainM1), a group of unit (viper), an item / vest or a class.

;! IMPORTANT : Using "\\" is possible, but you NEED to make sure that there are no space or any other character after.
;! The Xcom config parser removes the "\\" and put them in a single line, so the config is really :
; +PassiveAbilities=(AbilityTemplateName="AbilityTemplateName"AbilityName="Ability Name",EffectName="EffectName",Change=Traversal_BreakWall,Description="Passive traversal description.")

;! If you leave spaces after, the ability WILL break
;* Use https://robojumper.github.io/ue3-config-parser/index.html if you want to check

[TraversalChanger.X2Ability_TraversalChanger]

;* ===============================
;* PASSIVE ABILITIES
;* ===============================

;! These abilities are always active

; +PassiveAbilities=( \\
;     AbilityTemplateName="AbilityTemplateName"
;     AbilityName="Ability Name", \\
;     IconPath="UILibrary_PerkIcons.UIPerk_absorption_fields"
;     EffectName="EffectName", \\
;     Change="Traversal_BreakWall", \\
;     RemoveTraversal = false, \\
;     Description="Passive traversal description."
;   )

;? -----------------------------------
;? PASSIVE ABILITY DECOMPOSITION
;? -----------------------------------

;+PassiveAbilities=(
;* Create a new passive ability

;AbilityTemplateName="AbilityTemplateName"
;* The internal name, it cannot have spaces, this is what you'll add to the units / items

;AbilityName="Ability Name"
;* The name you see in game, can contain spaces

;IconPath="UILibrary_PerkIcons.UIPerk_absorption_fields"
;* The ability Icon

;EffectName="EffectName"
;* The effect that will be given, can be anything

;Change="Traversal_BreakWall"
;* The traversal change, below is a list of all traversal changes, note that some don't work / do anything without proper support

;Traversal_Normal --- Do not change, really, it might break the unit
;Traversal_ClimbOver --- Climb over objects (windows and such)
;Traversal_ClimbOnto --- Climb onto an object (untested)
;Traversal_ClimbLadder --- Climb ladders, water pipes...
;Traversal_DropDown ---  Drop down any height
;Traversal_Grapple --- Not tested, doesn't seem to do anything
;Traversal_Landing --- Used by the archon and drones (if using LWOTC or ABA, that's how they move around), if given only one traversal rule, issues may arise 
;Traversal_BreakWindow --- Break windows, pretty self explanatory
;Traversal_KickDoor ---  Kick doors, pretty self explanatory
;Traversal_WallClimb --- Climb walls
;Traversal_JumpUp --- Jump up walls
;Traversal_Ramp --- Do not change, really, it might break the unit
;Traversal_BreakWall --- Break walls
;Traversal_Phasing --- Phase through walls
;Traversal_Launch --- Used by the archon and drones (if using LWOTC or ABA, that's how they move around), if given only one traversal rule, issues may arise 
;Traversal_Flying --- Used by the archon and drones (if using LWOTC or ABA, that's how they move around), if given only one traversal rule, issues may arise 
;Traversal_Land --- Used by the archon and drones (if using LWOTC or ABA, that's how they move around), if given only one traversal rule, issues may arise 
;Traversal_Teleport --- Not tested, doesn't seem to do anything
;Traversal_Unreachable --- Not tested, doesn't seem to do anything
;Traversal_None --- Not tested, doesn't seem to do anything

;RemoveTraversal = false
;* Does the ability remove a traversal rule, instead of adding one.

;Description="Passive traversal description."
;* The ability's description

;* ===============================
;* ACTIVE ABILITIES
;* ===============================

; +ActiveAbilities=(
;     AbilityTemplateName="AbilityTemplateName", \\
;     AbilityName="AbilityName", \\
;     IconPath="UILibrary_PerkIcons.UIPerk_absorption_fields", \\
;     EffectName="AbilityEffectName", \\
;     Change="Traversal_Phasing", \\
;     Description="Active ability description.", \\
;     NumTurns=2, \\
;     AP_Cost=1, \\
;     IsFree=false, \\
;     ConsumeAllPoints=false, \\
;     Cooldown=2, \\
;     HasCharge=true, \\
;     InitialCharge=2
; )

;? -----------------------------------
;? ACTIVE ABILITY DECOMPOSITION
;? -----------------------------------

;+ActiveAbilities=(
;* Create a new active ability

;AbilityTemplateName="AbilityTemplateName"
;* The internal name, it cannot have spaces, this is what you'll add to the units / items

;AbilityName="Ability Name"
;* The name you see in game, can contain spaces

;IconPath="UILibrary_PerkIcons.UIPerk_absorption_fields"
;* The ability Icon

;EffectName="EffectName"
;* The effect that will be given, can be anything

;Change="Traversal_Phasing"
;* The traversal change

;Description="Passive traversal description."
;* The ability's description

;NumTurns=2
;* The amount of turns that the ability is active for

;AP_Cost=1
;* The action point cost

;IsFree=false
;* Is the ability free to use (no AP cost)

;ConsumeAllPoints=false
;* Does the ability consume all remaining AP (ie. always end the turn)

;Cooldown=2
;* The ability cooldown

;HasCharge=true
;* Does the ability have charges, if false, the values related to charge won't apply

;InitialCharge=2
;* Amount of charges available

;!!! ============================================ DEFAULT VALUES ==================================================

;* By default, if the values are ommited, it will use those :

; IconPath = "UILibrary_PerkIcons.UIPerk_absorption_fields"
; NumTurns = 2
; AP_Cost = 1
; IsFree = false
; ConsumeAllPoints = false
; Cooldown = 1
; HasCharge = false
; InitialCharge = 2

;* I recommend making abilities passive for AI units, as they won't know how to use them otherwise