[WOTC_TRMoreUpgrades.X2Item_TRMoreUpgrades]

; struct VestConversionData
; 	  var name VestTemplateName         - Template name of the vest to be converted to armor upgrade module
;     var array<name> GrantingTechs     - Techs that grant the vest. Only required if the vest is currently provided via tech
;     var array<name> Schematics        - Schematic that grants the vest. Only required if the vest is currently provided via schematic 
;     var bool ForceDefaultIcon         - For cases where the vest has ability with no icon image
;     var array<name> Abilities         - For special cases where not all abilities are copied form the vests. Can be used to add additional abilities to upgrade.
;     var bool bAllowOnSpark            - If true, allows this upgrade to be equipped by Sparks
;     var array<name> DisallowedArmors  - If populated, these armor templates cannot equip this upgrade

; struct AbilityConversionData
;     var name AbilityName              - Template name of the ability to be converted to armor upgrade module
;     var string strImg                 - Image to be used for the armor upgrade module
;     var bool ForceDefaultIcon         - For cases where the ability has no icon image
;     var bool bAllowOnSpark            - If true, allows this upgrade to be equipped by Sparks
;     var array<name> DisallowedArmors  - If populated, these armor templates cannot equip this upgrade

; IMPORTANT: Do not forget to adjust loot table if the current vests are dropped as loot item.

;* Dissalow for light armours, they already get it from XComRockClimb.ini
+arrVestsToConvert = (VestTemplateName = "TR_RockClimbingVest", DisallowedArmors = ("LightPlatedArmor", "LightPoweredArmor", "LightAlienArmor", "LightAlienArmorMk2"))
