[TraversalChanger.X2DLCInfo_TraversalChanger]
DLCIdentifier="TraversalChanger"

[TraversalChanger CHModDependency]
DisplayName="Traversal Changer"

;+IncompatibleMods="DLCIdentifier_Of_Some_Mod_A"

;+RequiredMods="WOTCIridarTemplateMaster"

;+IgnoreRequiredMods="DLCIdentifier_Of_Some_Mod_F"

; Commonly used modnames:

; PrototypeArmoury
; CovertInfiltration
; LongWarOfTheChosen
; XCOM2RPGOverhaul
; X2WOTCCommunityPromotionScreen
; PrimarySecondaries
; TruePrimarySecondaries
; DualWieldedPistols
; WOTC_LW2SecondaryWeapons


[TraversalChanger CHDLCRunOrder]
;+RunAfter=DLCIdentifier_A
;+RunBefore=DLCIdentifier_D

;RunPriorityGroup=RUN_FIRST
;RunPriorityGroup=RUN_STANDARD
;RunPriorityGroup=RUN_LAST